### ISSUE TITLE
I can't click select button all I don't get the blue button as indicated by you in screen

### ISSUE THREAD

**Issue by Starlord-199** [agusmoles/instagram-unfollowers#6]
I can't click select all button I don't get the blue button as indicated by you in screen since having so many I can't click all and 5000 can I know how to do to select all of them? thank you very much for your attention and if someone will help me.

**Comment by agusmoles** [comment]
hey @Starlord-199 !

Did you wait until the process of fetching all followed users finished?
![image](https://github.com/user-attachments/assets/3c32a877-bd0f-4759-b040-f371b758a31c)

It wont appear until you get to this point:
![image](https://github.com/user-attachments/assets/13ee948a-4d77-4c47-9d8c-b192506048e2)

How many users do you follow? Have you encountered any problem in the middle of the process?

Thank you!

**Comment by Starlord-199** [comment]
![image](https://github.com/user-attachments/assets/130580a1-afad-4464-bc3a-4cddd2a43930)

**Comment by Starlord-199** [comment]
![image](https://github.com/user-attachments/assets/c03c016b-59fa-435b-b22c-3ce362ac32af)

as you can see it doesn't give me these 2 followings this one in purple is your script while the one in black is instagram how can i do?? i want to remove them all...

**Comment by agusmoles** [comment]
Im not sure why there are 2 users missing on the fetching process. I just enabled the Select all button always, could you try now?

**Comment by Starlord-199** [comment]
![image](https://github.com/user-attachments/assets/64ba96f2-dacf-4de7-aeb4-6cfa4484605e)

Yeah it works you are the best thank you so much...you saved me i couldn't take it anymore seeing all these followers thank you so much man....  😍

**Comment by agusmoles** [comment]
haha they are a lot, no worries! Good luck 😄
